export { ProfilSejarah } from './sejarah'
export { ProfilVisi } from './visi'
export { ProfilStruktural } from './struktural'
export { ProfilProfil } from './profil'
export { ProfilGalery } from './galery'
